### ISSUE TITLE
DMRmmdvm keepalive timeout

### ISSUE THREAD

**Issue by coolacid** [nostar/urfd#6]
Good Day! First off, thank you for continuing the project and adding the keepalive to the TCP process. So far so good. 

I'm trying to track down a different keep-alive issue I've been seeing for a long time. I'm connecting to URFd from WPSD based hotspot. The connection constantly drops and reconnects. Logs from URFd;

```
DMRmmdvm connect packet from VE3YCA  B at <REDACTED>:59461
DMRmmdvm authentication packet from VE3YCA  B at <REDACTED>:59461
DMRmmdvm login from VE3YCA  B at <REDACTED>:59461
New client VE3YCA  B at <REDACTED>:59461 added with protocol DMRMmdvm
DMRmmdvm authentication packet from VE3YCA  B at <REDACTED>:59461
DMRmmdvm authentication packet from VE3YCA  B at <REDACTED>:59461
DMRmmdvm configuration packet from VE3YCA  B at <REDACTED>:59461
DMRmmdvm client VE3YCA  B linking on module A
Orphaned Frame with ID 60479 on <REDACTED>:59461
Orphaned Frame with ID 60479 on <REDACTED>:59461
DMRmmdvm client VE3YCA  B keepalive timeout
Client VE3YCA  B at <REDACTED>:39870 removed with protocol DMRMmdvm on module A
```

From DMRGateway
```
E: 2024-10-09 14:31:22.900 XLX, Connection to the master has timed out, retrying connection
M: 2024-10-09 14:31:22.900 XLX, Closing DMR Network
M: 2024-10-09 14:31:22.900 XLX, Opening DMR Network
M: 2024-10-09 14:31:22.901 XLX, Unlinking from XLXCA1 due to loss of connection
D: 2024-10-09 14:31:32.997 XLX, Sending authorisation
D: 2024-10-09 14:31:33.099 XLX, Sending configuration
M: 2024-10-09 14:31:43.126 XLX, Logged into the master successfully
M: 2024-10-09 14:31:43.127 XLX, Linking to reflector XLXCA1 A
```

I suspect it might be DMRGateway as the BM master is also timing out.

**Comment by coolacid** [comment]
After writing the ticket, and realising this is UDP and happening to both URFd and BM DMR connections I'm figuring it might be UDP connection tracking. I'm on a Unifi UDM Pro, and looks like the state timeouts for "UDP Other" is 30 seconds. I've bumped that to 180 and will report back.

**Comment by coolacid** [comment]
It may be a whole lot more embarrassing that the above. After I continued to see keepalive timeouts, I continued to investigate. 

When I ssh'd into the WPSD Raspberry Pi, I noticed my commands were slow and not always responding. Turns out, there was a lot of dropped packets. 

Just swapped out to a new Pi 4 and will report back.

**Comment by NA9VY** [comment]
@coolacid, did you figure this out? I'm having the same or similar issue with D-Star connections. Connecting with WPSD and going through a UDM Pro. My log will look like this and repeat about every one minute.

May 17 21:05:47 IndLink urfd[390365]: DCS client NA9VY   B keepalive timeout
May 17 21:05:47 IndLink urfd[390365]: Client NA9VY   B at 174.200.101.85:8328 removed with protocol DCS on module A
May 17 21:07:54 IndLink urfd[390365]: DCS connect packet for module A from NA9VY   B at 174.200.101.85:7581
May 17 21:07:54 IndLink urfd[390365]: New client NA9VY   B at 174.200.101.85:7581 added with protocol DCS on module A

NA9VY

**Comment by NA9VY** [comment]
I think I figure it out. I was in the process of renaming the URFD reflector (INL to 181). I had renamed the reflector in the ini file. The host files in the hotspot I was using the next evening had not been updated yet but the IP and Port were the same so it would try and connect. But, URFD no longer liked the old name (INL) and would bump the hotspot off. The hotspot would then connect again and the process would repeat.

Tonight the host files on the hotspot have updated and I'm connecting using the updated reflector name (181) and all seems to be stable.
